#!/usr/bin/env bash
# Regenerate the nginx real-ip config from Cloudflare's published ranges.
#
# Without this, every request arriving through Cloudflare is keyed by the CF
# edge that relayed it, collapsing a whole edge into one presence. The ranges
# change rarely; rerun this and redeploy the file when they do.
#
#   tools/gen-cloudflare-nginx.sh > deploy/cloudflare-realip.conf
set -euo pipefail

echo "# Generated by tools/gen-cloudflare-nginx.sh on $(date -u +%Y-%m-%d)."
echo "# Trust Cloudflare's edges to report the client, and nobody else (SPEC §5.3)."
for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
  curl -fsS --max-time 15 "$url" | grep -E '^[0-9a-fA-F:.]+/[0-9]+$' | sed 's/^/set_real_ip_from /; s/$/;/'
done
echo "real_ip_header CF-Connecting-IP;"
